# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [2, 2, 2]],
               [[3, 2, 2],
                [2, 2, 3]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

panda_df = pd.DataFrame(a2,
                        index=["I", "II"],
                        columns=["A", "B", "C"])
panda_df

A  B  C
I   1  2  3
II  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_int = np.random.randint(0, 10, size=(7,2))
random_int

array([[4, 1],
       [5, 5],
       [8, 2],
       [1, 2],
       [2, 6],
       [8, 8],
       [2, 5]])

In [13]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float = np.random.rand(3, 5)
random_float

array([[0.71942389, 0.2215243 , 0.32495114, 0.64518679, 0.81305966],
       [0.81091579, 0.11624428, 0.62914844, 0.3420244 , 0.10440787],
       [0.76226903, 0.11430736, 0.03763016, 0.22594907, 0.64029417]])

In [15]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_seed = np.random.randint(10, size=(4, 6))
random_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_num = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(random_num)

array([1, 2, 3, 4, 5, 7, 9])

In [17]:
random_num

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [18]:
# Find the 0'th index of the latest array you created
random_num[0, 0]

9

In [19]:
# Get the first 2 rows of latest array you created
random_num[:2, :]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [20]:
# Get the first 2 values of the first 2 rows of the latest array
random_num[:2, :2]

array([[9, 1],
       [5, 3]])

In [21]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1 = np.random.randint(10, size=(3,5))
arr2 = np.ones((3,5))

In [22]:
# Add the two arrays together
arr1 + arr2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [23]:
# Create another array of ones of shape (5, 3)
arr_ones = np.ones((5, 3))

In [24]:
# Try add the array of ones and the other most recent array together
arr_ones + arr2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [25]:
arr_ones = arr_ones.reshape(3, 5)

arr_ones + arr2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [26]:
# Create another array of ones of shape (3, 5)
array_ones = np.ones((3, 5))

In [27]:
arr1

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [28]:
# Subtract the new array of ones from the other most recent array
array_ones - arr1

array([[-5., -6., -1.,  1., -2.],
       [ 0., -6., -2.,  0., -4.],
       [-4., -8., -2., -4.,  0.]])

In [29]:
# Multiply the ones array with the latest array
array_ones * arr1

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [30]:
# Take the latest array to the power of 2 using '**'
arr1 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [31]:
# Do the same thing with np.square()
np.square(arr1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [32]:
# Find the mean of the latest array using np.mean()
np.mean(arr1)

3.8666666666666667

In [33]:
# Find the maximum of the latest array using np.max()
np.max(arr1)

9

In [34]:
# Find the minimum of the latest array using np.min()
np.min(arr1)

0

In [35]:
# Find the standard deviation of the latest array
np.std(arr1)

2.578543947441829

In [36]:
# Find the variance of the latest array
np.var(arr1)

6.648888888888889

In [37]:
arr1

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [38]:
# Reshape the latest array to (3, 5, 1)
arr1 = arr1.reshape(3, 5, 1)

In [39]:
arr1

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [40]:
arr1.shape

(3, 5, 1)

In [41]:
# Transpose the latest array
arr1.T

array([[[6, 1, 5],
        [7, 7, 9],
        [2, 3, 3],
        [0, 1, 5],
        [3, 5, 1]]])

In [42]:
arr1.T.shape

(1, 5, 3)

What does the transpose do?

In [48]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a = np.random.randint(10, size=(3, 3))
b = np.random.randint(10, size=(3, 2))

In [49]:
a

array([[9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [50]:
b

array([[6, 6],
       [7, 4],
       [2, 7]])

In [51]:
# Perform a dot product on the two newest arrays you created
c = np.dot(a, b)
c

array([[114, 141],
       [106, 128],
       [ 49,  46]])

In [53]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
aa = np.random.randint(10, size=(4, 3))
bb = np.random.randint(10, size=(4, 3))

In [54]:
aa

array([[5, 2, 0],
       [2, 4, 2],
       [0, 4, 9],
       [6, 6, 8]])

In [55]:
bb

array([[9, 9, 2],
       [6, 0, 3],
       [3, 4, 6],
       [6, 3, 6]])

In [56]:
# Perform a dot product on the two newest arrays you created
cc = np.dot(aa, bb)
cc

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [58]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
cc = np.dot(aa, bb.T)
cc

array([[ 63,  30,  23,  36],
       [ 58,  18,  34,  36],
       [ 54,  27,  70,  66],
       [124,  60,  90, 102]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [60]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
x = np.random.randint(10, size=(2, 2))
y = np.random.randint(10, size=(2, 2))

In [61]:
x

array([[2, 5],
       [1, 9]])

In [63]:
y

array([[8, 4],
       [5, 3]])

In [64]:
# Compare the two arrays with '>'
x > y

array([[False,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [65]:
# Compare the two arrays with '>='
x >= y

array([[False,  True],
       [False,  True]])

In [87]:
# Find which elements of the first array are greater than 7
x > 7

array([[False, False],
       [False,  True]])

In [70]:
# Which parts of each array are equal? (try using '==')
x == y

array([[False, False],
       [False, False]])

In [72]:
# Sort one of the arrays you just created in ascending order
np.sort(y)

array([[4, 8],
       [3, 5]])

In [74]:
# Sort the indexes of one of the arrays you just created
np.argsort(y)

array([[1, 0],
       [1, 0]])

In [76]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(y)

0

In [77]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(y)

3

In [78]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(x, axis=1)

array([1, 1])

In [79]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(x, axis=0)

array([1, 0])

In [89]:
# Create an array of normally distributed random numbers
normal = np.random.normal(0, 3, size=(2, 3))

# real solution
normal1 = np.random.randn(2, 3)

In [90]:
normal

array([[-5.75631365, -0.07954163,  0.18069063],
       [ 7.38972634, -0.57708289,  0.90464203]])

In [91]:
normal1

array([[-0.03471177, -1.16867804,  1.14282281],
       [ 0.75193303,  0.79103195, -0.90938745]])

In [92]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly = np.arange(0, 101, 10)
evenly

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [94]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.